spring:
  profiles:
    # # 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
    # #   测试环境：java -jar voicePlatform.jar --spring.profiles.active=test
    # #   生产环境：java -jar voicePlatform.jar --spring.profiles.active=product
    active: dev
  jpa:
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: false
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问，多个时，逗号隔开)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username:
        # 登录密码
        login-password:
      aop-patterns: com.cn.appmarket.web.mvc.controller.*,com.cn.appmarket.web.mvc.controller.*


  context-path: /
  jmx:
    default-domain: yrz
  jackson:
    default-property-inclusion: non_empty
#数据库加密使用的salt值
#jasypt.encryptor.password: e9fbdb2d3b21
project:
  name: '@project.name@'
  version: '@project.parent.version@'
  packageTime: '@timestamp@'

swagger:
  resourcePackage: com.driveasstes.controller
  title: 后台管理系统接口文档
  version: '@project.parent.version@'

# 解决swagger的官方文档中介绍是一个bug
# 在使用@ApiModelProperty注解在字段上时，如果字段的类型为Long或是int类型，
# 那么程序启动后，访问swagger-ui.html的页面，程序会报错
# java.lang.NumberFormatException: For input string: ""
# 添加下列配置
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error



